INSERT INTO wilaya (code, designation) VALUES (1, 'Adrar');
INSERT INTO wilaya (code, designation) VALUES (2, 'Chlef');
INSERT INTO wilaya (code, designation) VALUES (3, 'Laghouat');
INSERT INTO wilaya (code, designation) VALUES (4, 'Oum El Bouaghi');
INSERT INTO wilaya (code, designation) VALUES (5, 'Batna');
INSERT INTO wilaya (code, designation) VALUES (6, 'Béjaïa');
INSERT INTO wilaya (code, designation) VALUES (7, 'Biskra');
INSERT INTO wilaya (code, designation) VALUES (8, 'Béchar');
INSERT INTO wilaya (code, designation) VALUES (9, 'Blida');
INSERT INTO wilaya (code, designation) VALUES (10, 'Bouira');
INSERT INTO wilaya (code, designation) VALUES (11, 'Tamanrasset');
INSERT INTO wilaya (code, designation) VALUES (12, 'Tébessa');
INSERT INTO wilaya (code, designation) VALUES (13, 'Tlemcen');
INSERT INTO wilaya (code, designation) VALUES (14, 'Tiaret');
INSERT INTO wilaya (code, designation) VALUES (15, 'Tizi Ouzou');
INSERT INTO wilaya (code, designation) VALUES (16, 'Alger');
INSERT INTO wilaya (code, designation) VALUES (17, 'Djelfa');
INSERT INTO wilaya (code, designation) VALUES (18, 'Jijel');
INSERT INTO wilaya (code, designation) VALUES (19, 'Sétif');
INSERT INTO wilaya (code, designation) VALUES (20, 'Saïda');
INSERT INTO wilaya (code, designation) VALUES (21, 'Skikda');
INSERT INTO wilaya (code, designation) VALUES (22, 'Sidi Bel Abbès');
INSERT INTO wilaya (code, designation) VALUES (23, 'Annaba');
INSERT INTO wilaya (code, designation) VALUES (24, 'Guelma');
INSERT INTO wilaya (code, designation) VALUES (25, 'Constantine');
INSERT INTO wilaya (code, designation) VALUES (26, 'Médéa');
INSERT INTO wilaya (code, designation) VALUES (27, 'Mostaganem');
INSERT INTO wilaya (code, designation) VALUES (28, 'MSila');
INSERT INTO wilaya (code, designation) VALUES (29, 'Mascara');
INSERT INTO wilaya (code, designation) VALUES (30, 'Ouargla');
INSERT INTO wilaya (code, designation) VALUES (31, 'Oran');
INSERT INTO wilaya (code, designation) VALUES (32, 'El Bayadh');
INSERT INTO wilaya (code, designation) VALUES (33, 'Illizi');
INSERT INTO wilaya (code, designation) VALUES (34, 'Bordj Bou Arreridj');
INSERT INTO wilaya (code, designation) VALUES (35, 'Boumerdès');
INSERT INTO wilaya (code, designation) VALUES (36, 'El Tarf');
INSERT INTO wilaya (code, designation) VALUES (37, 'Tindouf');
INSERT INTO wilaya (code, designation) VALUES (38, 'Tissemsilt');
INSERT INTO wilaya (code, designation) VALUES (39, 'El Oued');
INSERT INTO wilaya (code, designation) VALUES (40, 'Khenchela');
INSERT INTO wilaya (code, designation) VALUES (41, 'Souk Ahras');
INSERT INTO wilaya (code, designation) VALUES (42, 'Tipaza');
INSERT INTO wilaya (code, designation) VALUES (43, 'Mila');
INSERT INTO wilaya (code, designation) VALUES (44, 'Aïn Defla');
INSERT INTO wilaya (code, designation) VALUES (45, 'Naâma');
INSERT INTO wilaya (code, designation) VALUES (46, 'Témouchent');
INSERT INTO wilaya (code, designation) VALUES (47, 'Ghardaïa');
INSERT INTO wilaya (code, designation) VALUES (48, 'Relizane');
INSERT INTO wilaya (code, designation) VALUES (49, 'Timimoun');
INSERT INTO wilaya (code, designation) VALUES (50, 'Bordj Badji Mokhtar');
INSERT INTO wilaya (code, designation) VALUES (51, 'Ouled Djellal');
INSERT INTO wilaya (code, designation) VALUES (52, 'Béni Abbès ');
INSERT INTO wilaya (code, designation) VALUES (53, 'In Salah');
INSERT INTO wilaya (code, designation) VALUES (54, 'In Guezzam');
INSERT INTO wilaya (code, designation) VALUES (55, 'Touggourt');
INSERT INTO wilaya (code, designation) VALUES (56, 'Djanet');
INSERT INTO wilaya (code, designation) VALUES (57, 'El MGhair');
INSERT INTO wilaya (code, designation) VALUES (58, 'El Meniaa');